import torch
import torch.nn as nn
import math
from config.config import cfg
import numpy as np
import torch.nn.functional as F


# Cut & paste from PyTorch official master until it's in a few official releases - RW
# Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf

def _no_grad_trunc_normal_(tensor, mean, std, a, b):  # 实现了对张量进行截断正态分布初始化的功能。
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        print("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
              "The distribution of values may be incorrect.", )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `model.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = model.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def shuffle_unit(features, shift, group, begin=1):
    batchsize = features.size(0)
    dim = features.size(-1)
    # Shift Operation
    feature_random = torch.cat([features[:, begin - 1 + shift:], features[:, begin:begin - 1 + shift]], dim=1)
    x = feature_random
    # Patch Shuffle Operation
    try:
        x = x.view(batchsize, group, -1, dim)
    except:
        x = torch.cat([x, x[:, -2:-1, :]], dim=1)
        x = x.view(batchsize, group, -1, dim)

    x = torch.transpose(x, 1, 2).contiguous()
    x = x.view(batchsize, -1, dim)

    return x


class Part_Attention(nn.Module):
    def __init__(self, ratio=0.5):
        super(Part_Attention, self).__init__()
        self.ratio = ratio

    def forward(self, x):
        length = len(x)
        N = x[0].shape[2] -1

        B = x[0].shape[0]
        k = 0
        last_map = x[k]

        # Using weighted sum or attention mechanism instead of pure multiplication
        for i in range(k + 1, length):
            last_map = torch.matmul(x[i], last_map)  # You can replace this with a more stable operation

        last_map = last_map[:, :, 0, 4:]  # Check if this slicing is necessary, consider making it dynamic

        max_index_set = None  # Initialize the index set outside the loop

        for i in range(last_map.shape[1]):
            _, topk_indices = torch.topk(last_map[:, i, :], int(N * self.ratio), dim=1)
            topk_indices = torch.sort(topk_indices, dim=1).values
            selected_tokens_mask = torch.zeros((B, N), dtype=torch.bool).cuda()
            selected_tokens_mask.scatter_(1, topk_indices, 1)

            # Directly accumulate selected tokens
            if max_index_set is None:
                max_index_set = selected_tokens_mask
            else:
                max_index_set = max_index_set | selected_tokens_mask

        return max_index_set


class SFTS(
    nn.Module):  # 根据输入的特征和注意力张量，选择性地提取特定的特征子序列，并将其融合到一起，以产生更具信息量的特征表示。在训练阶段，模块还会通过计算背景损失来监督特征的选择，以确保选择的特征与背景特征之间的一致性。
    def __init__(self, ratio=0.5):
        super(SFTS, self).__init__()
        self.part_select = Part_Attention(ratio=ratio)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, RGB_feat, RGB_attn, NIR_feat=None, NIR_attn=None, img_path=None, label=None,
                writer=None, epoch=None, mask_fre=None):
        RGB_index = self.part_select(RGB_attn)
        NIR_index = self.part_select(NIR_attn)
        original_index = RGB_index | NIR_index

        index = (original_index | mask_fre).unsqueeze(-1)  # 表示了扩展后或修正后的选择性子序列的索引，可以用于在特征张量中选择对应位置的特征。
        RGB_parts = RGB_feat[:, 1:, :] * index
        NIR_parts = NIR_feat[:, 1:, :] * index

        RGB_feats = torch.cat([RGB_feat[:, 0].unsqueeze(1), RGB_parts], dim=1)
        NIR_feats = torch.cat([NIR_feat[:, 0].unsqueeze(1), NIR_parts], dim=1)
        # 用于从 RGB 和 NIR 特征张量中选择性地提取特定位置的特征，并将其与原始特征序列拼接起来，以形成新的特征序列
        if self.training:
            bgindex = ~index
            RGB_bg = RGB_feat[:, 1:, :] * bgindex
            NIR_bg = NIR_feat[:, 1:, :] * bgindex
            # RGB_bg_JPM = shuffle_unit(RGB_bg,4,2)
            # NIR_bg_JPM = shuffle_unit(NIR_bg,4,2)
            loss_bg = nn.MSELoss()(RGB_bg, NIR_bg)
            return RGB_feats, NIR_feats, index, loss_bg
        else:
            return RGB_feats, NIR_feats, index