DATASET: 'regdb'

START_EPOCH: 1
MAX_EPOCH: 68
BATCH_SIZE: 16
NUM_POS: 4
FREQUENCY_KEEP: 14
STRIDE_SIZE: [14,14]
# PMT
METHOD: 'PMT'  # 'PMT' or 'base'
PL_EPOCH: 6
MSEL: 0.5
DCL: 0.5
MARGIN: 0.1
cmsm: 0.25
tri2: 0.25
k1: 0
k2: 0