DATASET: 'llcm'

START_EPOCH: 1
MAX_EPOCH: 34

BATCH_SIZE: 32
NUM_POS: 4
STRIDE_SIZE: [14,14]
FREQUENCY_KEEP: 14

METHOD: 'PMT'  # 'PMT' or 'base'
PL_EPOCH: 6
MSEL: 0.5
DCL: 0.5
MARGIN: 0.1
cmsm: 0.0
